---
openapi: "3.0.3"
info:
  version: "0.0.1"
  title: "External reference assessment case: {case}"
paths:
  /foos:
    get:
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: schema.yaml
